export * from './logExternalAPIRequest.model'

// 权限 后期砍掉
export * from './auth/menu'
export * from './auth/organize'
export * from './auth/role'
export * from './auth/roleMenu'
export * from './auth/userRole'
export * from './auth/roleOrganize'
export * from './auth/user'
export * from './auth/team'
export * from './auth/teamUser.model'
export * from './auth/teamEquipmentLedger.model'
export * from './auth/teamProcess.model'

// 基础资料 base
export * from './base/material.model'
export * from './base/bom.model'
export * from './base/bomDetail.model'
export * from './base/supplier.model'
export * from './base/workShop.model'
export * from './base/customer.model'
export * from './base/pallet.model'
export * from './base/palletDetail.model'
export * from './production/POPSchedule'
// 动态表单
export * from './base/trendsTemplate.model'
export * from './base/trendsField.model'

// 系统管理 system
export * from './system/apiConfig.model'
export * from './system/apiDict.model'
export * from './system/printTemplate.model'
export * from './system/dynamicForm.model'
export * from './system/dynamicFormData.model'
export * from './system/dynamicFormRule.model'

//质量管理 quality
export * from './quantity/defectiveItem.model'
export * from './quantity/inspectionItem.model'
export * from './quantity/inspectionTemplate.model'
export * from './quantity/inspectionTemplateItem.model'
export * from './quantity/inspectionTemplateMat.model'
export * from './quantity/inspectionForm.model'
export * from './quantity/inspectionFormBy.model'
export * from './quantity/InspectionFormItem.model'
export * from './quantity/InspectionFormItemRecord.model'
export * from './quantity/batchLog.model'
export * from './quantity/inspectionFormInfo.model'
export * from './quantity/inspectionFormResult.model'

//工序管理  process
export * from './process/process.model'
export * from './process/processItems.model'
export * from './process/processDept.model'
export * from './process/processRoute.model'
export * from './process/processRouteList.model'
export * from './process/processRouteListItem.model'
export * from './process/SOP.model'
export * from './process/SOPMaterial.model'
export * from './process/SOPFile.model'
export * from './process/SOParameter.model'

//文件管理 document
export * from './document/FileMenu.model'
export * from './document/FileList.model'
export * from './document/FileVersion.model'

//生产计划 plan
export * from './plan/salesOrder.model'
export * from './plan/salesOrderDetail.model'

//生产执行 production
export * from './production/productionOrder.model'
export * from './production/productionOrderDetail.model'
export * from './production/productionOrderTask.model'
export * from './production/productSerial.model'
export * from './production/PODmodel'
export * from './production/POI.model'
export * from './production/POB.model'
export * from './production/POBDetail.model'
export * from './production/processTask.model'
export * from './production/processTaskDept.model'
export * from './production/productionReport.model'
export * from './production/productionReportDetail.model'
export * from './production/productionOrderTaskOfReport'
export * from './production/PRI.model'
export * from './production/productionOutsourcing.model' //工序委外
export * from './production/processTaskLog.model'
export * from './production/userTaskDuration.model'
export * from './production/userDuration.model'
export * from './production/productionOrderTaskOfTeam.model'
export * from './production/processPositionTask.model'
export * from './production/ironProductSerial.model'
export * from './production/position.model'
export * from './production/positionDetail.model'
export * from './production/positionTaskDetail.model'

// 派工
export * from './production/processLocate.model'
export * from './production/processLocateDetail.model'

//绩效管理 performance
export * from './performance/performance.model'
export * from './performance/performanceConfig.model'
export * from './performance/performanceDetailed.model'
export * from './performance/manHour.model'
export * from './performance/manHourProcess.model'
export * from './performance/performancePrice.model'
export * from './performance/performancePriceDetail.model'
export * from './performance/performanceTotal.model'

//排班管理 schedule
export * from './schedule/shift.model'
export * from './schedule/shiftPeriod.model'
export * from './schedule/calendar.model'
export * from './schedule/calendarDetail.model'
export * from './schedule/schedulePlan.model'
export * from './schedule/schedulePlanShift.model'
export * from './schedule/planShiftTeam.model'
export * from './schedule/notify.model'

//库存管理 warehouse
export * from './warehouse/warehouse.model'
export * from './warehouse/warehouseMaterial.model'
export * from './warehouse/inboundOrder.model'
export * from './warehouse/inboundOrderDetail.model'
export * from './warehouse/outboundOrder.model'
export * from './warehouse/outboundOrderDetail.model'
export * from './warehouse/adjustOrder.model'
export * from './warehouse/adjustOrderDetail.model'
export * from './warehouse/transferOrder.model'
export * from './warehouse/transferOrderDetail.model'
export * from './warehouse/materialRequisition.model'
export * from './warehouse/materialRequisitionDetail.model'
export * from './warehouse/exportOrder.model'
export * from './warehouse/exportOrderDetail.model'
export * from './warehouse/PRO.model'
export * from './warehouse/PRODetail.model'

//设备管理 equipment
export * from './equipment/equipment.model'
export * from './equipment/equipmentType.model'
export * from './equipment/installLocation.model'
export * from './equipment/checkStandard.model'
export * from './equipment/checkStandardDetail.model'
export * from './equipment/inspectionPlan.model'
export * from './equipment/inspectionPlanDetail.model'
export * from './equipment/equipmentLedger.model'
export * from './equipment/checkOrder.model'
export * from './equipment/checkOrderDetail.model'
export * from './equipment/inspectionOrder.model'
export * from './equipment/inspectionOrderDetail.model'
export * from './equipment/repairOrder.model'
export * from './equipment/repairOrderDetail.model'
export * from './equipment/repairOrderResult.model'
export * from './equipment/repairOrderReceive.model'
export * from './equipment/maintenancePlan.model'
export * from './equipment/maintenancePlanDetail.model'
export * from './equipment/maintenanceOrder.model'
export * from './equipment/maintenanceOrderDetail.model'
export * from './equipment/scrapOrder.model'

// 数据中台 center
export * from './center/dcNotify.model'
export * from './center/drawing.model'
export * from './center/craft.model'
