export * from './logExternalAPIRequest.model'

// 基础资料 base
export * from './base/material.model'
export * from './base/bom.model'
export * from './base/bomSubItem.model'
export * from './base/supplier.model'
export * from './base/workShop.model'
export * from './base/workCenter.model'
export * from './base/customer.model'
export * from './base/workCenterOfPOP.model'
// 动态表单
export * from './base/trendsTemplate.model'
export * from './base/trendsField.model'

// 系统管理 system
export * from './sys/SYSMenu.model'
export * from './sys/SYSOrg.model'
export * from './sys/SYSRole.model'
export * from './sys/SYSRoleMenu.model'
export * from './sys/SYSUserRole.model'
export * from './sys/SYSRoleOrg.model'
export * from './sys/user.model'
export * from './sys/apiConfig.model'
export * from './sys/apiDict.model'
export * from './sys/printTemplate.model'

//质量管理 quality
export * from './quantity/defectiveItem.model'
export * from './quantity/inspectionItem.model'
export * from './quantity/inspectionTemplate.model'
export * from './quantity/inspectionTemplateItem.model'
export * from './quantity/inspectionTemplateMat.model'
export * from './quantity/inspectionForm.model'
export * from './quantity/inspectionFormBy.model'
export * from './quantity/InspectionFormItem.model'
export * from './quantity/InspectionFormItemRecord.model'
export * from './quantity/batchLog.model'
export * from './quantity/inspectionFormInfo.model'
export * from './quantity/inspectionFormResult.model'

//工序管理  process
export * from './process/process.model'
export * from './process/processItems.model'
export * from './process/processDept.model'
export * from './process/processRoute.model'
export * from './process/processRouteList.model'
export * from './process/processRouteListItem.model'
export * from './process/SOP.model'
export * from './process/SOPMaterial.model'
export * from './process/SOPFile.model'

//文件管理 document
export * from './document/FileMenu.model'
export * from './document/FileList.model'
export * from './document/FileVersion.model'

//生产计划 plan
export * from './plan/salesOrder.model'
export * from './plan/salesOrderDetail.model'

//生产执行 production
export * from './production/productionOrder.model'
export * from './production/POP.model'
export * from './production/PODmodel'
export * from './production/POI.model'
export * from './production/POB.model'
export * from './production/POBD.model'
export * from './production/processTask.model'
export * from './production/processTaskDept.model'
export * from './production/processTaskUser.model'
export * from './production/productionReport.model'
export * from './production/PRI.model'
export * from './production/productionOutsourcing.model' //工序委外
export * from './production/processTaskLog.model'
export * from './production/reportUser.model'
export * from './production/reportUserDuration.model'

//绩效管理 performance
export * from './performance/performance.model'
export * from './performance/performanceConfig.model'
export * from './performance/performanceDetailed.model'
export * from './performance/manHour.model'
export * from './performance/manHourProcess.model'

//排班管理 schedule
export * from './schedule/teamType.model'
export * from './schedule/team.model'
export * from './schedule/teamUser.model'
export * from './schedule/shift.model'
export * from './schedule/shiftPeriod.model'
export * from './schedule/calendar.model'
export * from './schedule/calendarDetail.model'
export * from './schedule/schedulePlan.model'
export * from './schedule/schedulePlanShift.model'
export * from './schedule/planShiftTeam.model'
export * from './schedule/teamEquipmentLedger.model'
export * from './schedule/teamProcess.model'
export * from './schedule/notify.model'

//库存管理 warehouse
export * from './warehouse/warehouse.model'
export * from './warehouse/warehouseMaterial.model'
export * from './warehouse/inboundOrder.model'
export * from './warehouse/inboundOrderDetail.model'
export * from './warehouse/outboundOrder.model'
export * from './warehouse/outboundOrderDetail.model'
export * from './warehouse/adjustOrder.model'
export * from './warehouse/adjustOrderDetail.model'
export * from './warehouse/transferOrder.model'
export * from './warehouse/transferOrderDetail.model'
export * from './warehouse/materialRequisition.model'
export * from './warehouse/materialRequisitionDetail.model'
export * from './warehouse/exportOrder.model'
export * from './warehouse/exportOrderDetail.model'
export * from './warehouse/PRO.model'
export * from './warehouse/PRODetail.model'

//设备管理 equipment
export * from './em/equipment.model'
export * from './em/equipmentType.model'
export * from './em/installLocation.model'
export * from './em/checkStandard.model'
export * from './em/checkStandardDetail.model'
export * from './em/inspectionPlan.model'
export * from './em/inspectionPlanDetail.model'
export * from './em/equipmentLedger.model'
export * from './em/checkOrder.model'
export * from './em/checkOrderDetail.model'
export * from './em/inspectionOrder.model'
export * from './em/inspectionOrderDetail.model'
export * from './em/repairOrder.model'
export * from './em/repairOrderDetail.model'
export * from './em/repairOrderResult.model'
export * from './em/repairOrderReceive.model'
export * from './em/maintenancePlan.model'
export * from './em/maintenancePlanDetail.model'
export * from './em/maintenanceOrder.model'
export * from './em/maintenanceOrderDetail.model'
export * from './em/scrapOrder.model'

// 数据中台 center
export * from './io/dcNotify.model'
export * from './io/drawing.model'
export * from './io/craft.model'
